### ISSUE TITLE
I created a NC 14 compatible fork (maybe even 15)

### ISSUE THREAD

**Issue by jayarc** [e-alfred/ocdownloader#108]
I have forked the latest db-rework2 branch and tried to fix some of the UI things going on there. I also modified the youtube.php file to use the linux which command to find the proper path, it was failing for me to get the Youtube URL because it wasn't getting the youtube-dl path right.

To use the fork on NC 14+ issue this command inside your nextcloud apps directory:
git clone --single-branch --branch nc-14 https://github.com/jayarc/ocdownloader.git

**Comment by jayarc** [comment]
If there are pieces that would be useful as a PR, can do.

**Comment by blackcrack** [comment]
try to contact e-alfred, if this not possible thing one month, rename your ocdownloader to ocdownloader2 and try to contact the developer over the issues tread and make it like e-alfred it done, overtake the project and make further.., i have it make like so up to e-alfred it take over.. so, if you want make further....
go to the best issue treads and contact/say the peoples, there is a way to make further ..
i don't know how old e-alfred or if he sick or something, but if the actually project so sluggish also with including the patches and so..
1. you have a Realname (i want stay hidden, because my whole "work '0X' in the starting time" i will never give my name in the internet in connect of my real name (my alias is older as 20 years ..)..)
2. you're be young,.. enough to maintaining a very long time (i am over 45 and be sick)
3. i see in your Userpicture, you have a so far stable Social stand .. (free of negative drugs and so on)
4. and you have the will ..

If e-alfred still exist, should he take you in the ocdownloader Memberlist ..
to have later a successor or maybe 2 or 3 to have a secure for the ocdownloader project continues.

so, stand nothing in the way for continues the ocdownloader.. :+1: 
Alone the fact to i am posting here.. and you want maintaining further ..

so, i cross the fingers for you.
best regards
Blacky

i am support open source, Freeware and programming  a bit php,html  and my home is the blackysgate.de \ net and www.efb.nu freeware Forum as member ..  without razio anymore

**Comment by DocSniper** [comment]
Did you test this fork on NC 15 ?  Because I'm getting errors on my NC 15 installation. 
Maybe it's specific problem with my installation, but here the log:

[index] Error: Error: Class 'OCP\DB' not found at <<closure>>

 0. /usr/share/webapps/nextcloud/apps/ocdownloader/controller/lib/tools.php line 187
    getValue()
 1. /usr/share/webapps/nextcloud/apps/ocdownloader/controller/index.php line 47
    canCheckForUpdate()
 2. /usr/share/webapps/nextcloud/apps/ocdownloader/appinfo/application.php line 44
    __construct("ocdownloader", OC\AppFramework\Http\Request {}, "username", OC\L10N\L10N {})
 3. /usr/share/webapps/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\ocDownloader\AppInfo\{closure}("*** sensitive parameters replaced ***")
 4. /usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 117
    offsetGet("IndexController")
 5. /usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 418
    query("IndexController")
 6. /usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 396
    queryNoFallback("IndexController")
 7. /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php line 95
    query("IndexController")
 8. /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("IndexController", "Add", "*** sensitive parameter replaced ***", {_route: "ocdownloader.Index.Add"})
 9. <<closure>>
    __invoke({_route: "ocdownloader.Index.Add"})
10. /usr/share/webapps/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Add"})
11. /usr/share/webapps/nextcloud/lib/base.php line 987
    match("/apps/ocdownloader/add")
12. /usr/share/webapps/nextcloud/index.php line 42
    handleRequest()

**Comment by Goeste** [comment]
I can provide the fllowing error after enabling OCD via CLI

`    /www/htdocs/xxx/next.domain.de/apps/ocdownloader/controller/lib/tools.php - line 187:
    OCA\ocDownloader\Controller\Lib\Settings->getValue()
    /www/htdocs/xxx/next.domain.de/apps/ocdownloader/controller/index.php - line 47:
    OCA\ocDownloader\Controller\Lib\Tools::canCheckForUpdate()
    /www/htdocs/xxx/next.domain.de/apps/ocdownloader/appinfo/application.php - line 44:
    OCA\ocDownloader\Controller\Index->__construct("ocdownloader", OC\AppFramework\Http\Request {}, "goeste", OC\L10N\L10N {})
    /www/htdocs/xxx/next.domain.de/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:
    OCA\ocDownloader\AppInfo\Application->OCA\ocDownloader\AppInfo\{closure}("*** sensiti ... *")
    /www/htdocs/xxx/next.domain.de/lib/private/AppFramework/Utility/SimpleContainer.php - line 117:
    Pimple\Container->offsetGet("IndexController")
    /www/htdocs/xxx/next.domain.de/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 446:
    OC\AppFramework\Utility\SimpleContainer->query("IndexController")
    /www/htdocs/xxx/next.domain.de/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 424:
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("IndexController")
    /www/htdocs/xxx/next.domain.de/lib/private/AppFramework/App.php - line 95:
    OC\AppFramework\DependencyInjection\DIContainer->query("IndexController")
    /www/htdocs/xxx/next.domain.de/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
    OC\AppFramework\App::main("IndexController", "Add", "*** sensiti ... *", { _route: "o ... "})
    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "o ... "})
    /www/htdocs/xxx/next.domain.de/lib/private/Route/Router.php - line 297:
    call_user_func(OC\AppFramew ... {}, { _route: "o ... "})
    /www/htdocs/xxx/next.domain.de/lib/base.php - line 987:
    OC\Route\Router->match("/apps/ocdownloader/add")
    /www/htdocs/xxx/next.domain.de/index.php - line 42:
    OC::handleRequest()`

**Comment by jayarc** [comment]
It looks like 15 support will take more work to rewrite some database queries for the new 15 QueryBuilder. I may have time soon to do this, we'll see. Anybody else who has ideas?

**Comment by e-alfred** [comment]
@jayarc Thanks for you work! I added the CSS fixes to the db-rework2 branch and pushed a new testing release to the Nextcloud app store.

There are a few bugs at the moment:

- Personal settings page doesn't work
- API for extensions doesn't work (maybe an upstream bug?)

**Comment by jayarc** [comment]
@e-alfred I can see about those two items in the next week here some time.

**Comment by e-alfred** [comment]
@jayarc Thanks for your help, if we can fix those two problems I would like to publish a final version to the App Store.

@DrKinSlayeR The only thing you can set on the personal settings page is the download folder. Everything else is done in the admin settings which work flawlessly.

**Comment by AkgunFatih** [comment]
> @jayarc Thanks for your work! I added the CSS fixes to the db-rework2 branch and pushed a new testing release to the Nextcloud app store and to the Github releases page:
> 
> https://github.com/e-alfred/ocdownloader/releases/tag/1.6.0-Alpha1
> 
> There are a few bugs at the moment:
> 
> * Personal settings page doesn't work
> * API for extensions doesn't work (maybe an upstream bug?)
> 
> If anyone wants to help fix these remaining problems I would greatly appreciate that!

is this a joke ?
<nextcloud min-version="11" max-version="13" />

**Comment by e-alfred** [comment]
@AkgunFatih Sorry for the mistake, just change "13" to "15" for now.

**Comment by AkgunFatih** [comment]
> @AkgunFatih Sorry for the mistake, just change "13" to "15" for now.

i did but when i browse to apps/ocdownloader/add i get internal error
this is the error log

```
[index] Error: Error: Class 'OCP\DB' not found at <<closure>>

 0. /config/www/nextcloud/apps/ocdownloader/controller/lib/tools.php line 187
    getValue()
 1. /config/www/nextcloud/apps/ocdownloader/controller/index.php line 47
    canCheckForUpdate()
 2. /config/www/nextcloud/apps/ocdownloader/appinfo/application.php line 44
    __construct("ocdownloader", OC\AppFramework\Http\Request {}, "hqusertr", OC\L10N\L10N {})
 3. /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\ocDownloader\AppInfo\{closure}("*** sensitive parameters replaced ***")
 4. /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 117
    offsetGet("IndexController")
 5. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 418
    query("IndexController")
 6. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 396
    queryNoFallback("IndexController")
 7. /config/www/nextcloud/lib/private/AppFramework/App.php line 95
    query("IndexController")
 8. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("IndexController", "Add", "*** sensitive parameter replaced ***", {_route: "ocdownloader.Index.Add"})
 9. <<closure>>
    __invoke({_route: "ocdownloader.Index.Add"})
10. /config/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Add"})
11. /config/www/nextcloud/lib/base.php line 987
    match("/apps/ocdownloader/add")
12. /config/www/nextcloud/index.php line 42
    handleRequest()

GET /index.php/apps/ocdownloader/add
from 172.19.0.7 by hqusertr at 2019-01-22T21:47:40+00:00
```
im gonna try to fix it, but i cant promise :)

**Comment by AkgunFatih** [comment]
@e-alfred did you look at this [changelog ](https://docs.nextcloud.com/server/stable/developer_manual/app/changelog.html?highlight=OCP\DB)?

**Comment by AkgunFatih** [comment]
i wasted hours trying to fix it but then i realized you already fixed  it https://github.com/e-alfred/ocdownloader/tree/db-rework2

Thank you for not telling us here and wasting our time.. time to delete it.

**Comment by e-alfred** [comment]
@AkgunFatih Please be a bit more polite. You seem to use the master branch which is not compatible with Nextcloud 14 and up which you didn't menition in the first place. I created a rework branch with my fixes plus those from @jayarc and published an alpha release on the App Store (marked as nightly) and on the releases page of this repository and linked it in the main issues regarding these problems. This release has two known issues but otherwise works well on Nextcloud 14 and up. As soon as those issues are fixed I will publish a final release to the App Store.

**Comment by CHazz** [comment]
any news ? I'm slowly dying .. thanks

**Comment by bekon16** [comment]
+1 - any ETA? :)

**Comment by blackcrack** [comment]
and i am go drying out .. i have slowly dry lips
@e-alfred make me wet.. eehhh on the lips ehhh.... damn.. ! 
with a fresh version :)

**Comment by blackcrack** [comment]
https://github.com/e-alfred/ocdownloader/releases/tag/1.6.1

jeeeehhhyyyyy :))))))) :1st_place_medal: 

wet, hot and ..... damnn crewl ! thy :)

**Comment by CHazz** [comment]
thank you very much ! working great with nextcloud 15 now :)
