### ISSUE TITLE
Create standalone ocdownloader package or docker image

### ISSUE THREAD

**Issue by nebula-it** [e-alfred/ocdownloader#128]
**This is not an issue with ocDownloader** 
Hello folks,

For a long time I have been looking for a downloader that runs in a docker container and everything is accessible over a webui. I just came across ocDownloader and it seems like it ticks all the boxes (two big ones: Aria and youtube-dl integration) however it is not a standalone utility and is an addon for NC/OC. I was wondering if this can be spun off into its own complete package that can be used without NC/OC. So here are some questions I'm seeking answers for:

1. Does ocDownloader relies on OC/NC for anything other than the webgui?
2. How hard will it be to implement  a standalone webgui for it?
3. Would you be interested in one such package or a docker image?

**Comment by blackcrack** [comment]
dogger.. bullschit,, like the thing with Libreoffice.. Collabora ..
i hope it give never a doggerbullshit for .. 
i hope it stay in future as "simple" save and good downloader for our cloud ..
and this is my opinion about, this is not a issue, this is a crap, should be closed.... !
sorry for my hard words.. but well .. i use not the f. word *bg*

**Comment by Happyfeet01** [comment]
Look here vor an separate Container for Aria2 [https://paste.dasnetzundich.de/view/ea94d3f8](url) but ocdownloader can reach it. I don't how is it possible.

**Comment by e-alfred** [comment]
@nebula-it Well to answer your questions:

1. ocDownloader relies on a lot of Owncloud/Nextcloud APIs, but it is only an app inside Nextcloud providing a nice web UI and relies on external tools like Aria2, Curl and Youtube-dl to work correctly. Rewriting might be possible, but it will be a lot of work and you would have to do a lot of things from scratch provided by the Nextcloud API.
2. I am not sure, but given 1. maybe improving an existing tool like aria2-web would be more useful than starting from scratch or rewrite ocDownloader: https://github.com/ziahamza/webui-aria2/
The most important part it misses is youtube-dl integration, otherwise the features should match pretty much.
3. If you can help to make something like that, it would be interesting of course. As a compromise you could make Nextcloud docker container that focuses heavily on ocDownloader (like for example starting ocDownloader as the default app instead of the files app and removing almost all unnecessary apps like calendar, contacts etc) packing in Aria2c, youtube-dl and providing an external storage space where downloads can be stored using a Docker environment variable. The Dockerfile to build something like that could be pushed into a Github repository and the final container image could be pushed to the Docker Hub then.

**Comment by nebula-it** [comment]
Thank you for the detailed reply, appreciate all the info. I looked at few other options and then went with https://github.com/Tzahi12345/YoutubeDL-Material and that has been working very well for my use case.
