### ISSUE TITLE
Unable to retrieve true YouTube video URL version:1.7.8

### ISSUE THREAD

**Issue by xspeed1989** [e-alfred/ocdownloader#173]
Unable to retrieve true YouTube video URL
```bash
root@082a294e6759:/var/www/html/config# /usr/local/bin/youtube-dl
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

![image](https://user-images.githubusercontent.com/5162926/88135249-2a0d8800-cc19-11ea-9268-592070e1f9ce.png)

@e-alfred

**Comment by xspeed1989** [comment]
i just modify the default path in the source file, it will be ok
so i think there is a issue when save config of youtube-dl

@e-alfred

**Comment by xspeed1989** [comment]
i modify you source code  and put my password in source file instead read from setting,it woks fine
@e-alfred

**Comment by e-alfred** [comment]
It seems like your settings aren't correct. it should be `bestaudio[abr<=75]` and `best[width<=1280]`, otherwise you stumble into this problem: https://github.com/e-alfred/ocdownloader/issues/29

**Comment by e-alfred** [comment]
What database type do you use? Can you check in your Nextcloud database if the settings in oc_ocdownloader_adminsettings are correct?

**Comment by xspeed1989** [comment]
my database is sqlite

**Comment by e-alfred** [comment]
Well, SQLite isn't well supported by ocDownloader, only Mariadb/Mysql and Postgresql are fully supported. SQLite is also not well supported by Nextcloud itself except for minimal instances. Can you migrate your instance to Mysql or Mariadb? This would also increase the performance of your Nextcloud installation.

The database file for SQLite should be located in your Nextcloud directory, you should be able to find the path to it in your config.php as well.

**Comment by grondinm** [comment]
I'm getting the same error NC19 OCDownload V1.7.8. But when i try youtubedl from CLI i get

YouTube said: Unable to extract video data

So Youtube broke something and will need an updated youtube-dl...unless this issue is something different.

**Comment by evijayan2** [comment]
I have the same issue
NextCloud 19.0.1
DB: mysql
OCDownloader 1.7.8
Settings
<img width="610" alt="Screen Shot 2020-07-28 at 4 54 59 PM" src="https://user-images.githubusercontent.com/1349005/88720610-22efe980-d0f3-11ea-8dd9-a33f7704abfb.png">
<img width="1020" alt="Screen Shot 2020-07-28 at 4 56 00 PM" src="https://user-images.githubusercontent.com/1349005/88720676-3e5af480-d0f3-11ea-8b0b-a87b804a8e10.png">


**Unable to retrieve true YouTube video URL**

**Comment by weiwang11** [comment]
I have the same issue as well.

NextCloud 18.0.7
DB: mysql
OCDownloader 1.7.8

I can download from youtube-dl just fine as well as using the web extension: https://addons.mozilla.org/en-US/firefox/addon/ocdownloader-extension/ which would download directory to the user's nextcloud folder.

Both curl and aria2 however produces the same "Unable to retrieve true YouTube video URL" message when trying to launch the download on the ocDownloader page on NextCloud.

**Comment by jonathanmmm** [comment]
I am on Nextcloud 19 with the newest version of this app and nothing seemed to work.
Path is /usr/local/bin/youtube-dl

BUT the following command via ssh made it possible, dont know why:
sudo cp /usr/local/bin/youtube-dl /usr/bin/youtube-dl

**Comment by NerdSnapper** [comment]
I have the same issue like evijayan,

still not working from Nextcloud.
from ssh shell it works just fine.

Centos8
Nextcloud 19.03
ocDownloader 1.78
db: mariaDB

nothing of the above helped...

**Comment by NerdSnapper** [comment]
I found the solution for me: (it's a system issue)

someone gave me the hint to disable selinux because this may block the webserver traffic outbound.

after disableing selinux, the error message disabled (but I got another error I will have to solve).

Centos 8 (and also Ubuntu Server from 20) has selinux enforced after installation.
For others: please check /etc/selinux/config

If you are familiar with the granular configuration of selinux, of course you can set the correct permissions in selinux for that instead.

**Comment by tatrnka** [comment]
I had the same problem.

**ocdownloader webextension** error message
"unable to retrieve true youtube video url"

**youtube-dl** error message
"YouTube said: Unable to extract video data"

So I tried
`sudo -H pip install --upgrade youtube-dl`

After upgrade it works again.

**Comment by tatrnka** [comment]
I had the same problem.

ocdownloader webextension error message
"unable to retrieve true youtube video url"

youtube-dl error message
"YouTube said: Unable to extract video data"

So I tried
sudo -H pip install --upgrade youtube-dl

After upgrade it works again from both, command line and webextension too.

**Comment by tatrnka** [comment]
I had the same problem.

**ocdownloader webextension** error message
"unable to retrieve true youtube video url"

**youtube-dl** error message
"YouTube said: Unable to extract video data"

So I tried
`sudo -H pip install --upgrade youtube-dl`

After upgrade it works again from both, command line and webextension too.

**Comment by e-alfred** [comment]
@tatodorov Yes, you have to keep your youtube-dl package updated regularly because the pages supported by it change all the time. Best is to set up a Cron job to do it automatically.

**Comment by roboticsalign** [comment]
I had the same issue and found a log entry:
`sh: 1: /usr/bin/youtube-dl: not found`

But my UI showed the correct path:
![image](https://user-images.githubusercontent.com/23562360/103463547-6f3bf700-4d2d-11eb-8c2b-7e2f9ec8d417.png)

For me the solution was to reset the path of the binary by clearing the box in the UI and adding the correct path again. I hope, that helps somebody.

**Comment by mvhirsch** [comment]
I'm too having troubles with youtube-dl. Looks like settings won't be set correctly?
I'm using a docker-based setup, using `nextcloud:20` and mysql. I've installed youtube-dl using `apt-get install youtube-dl`.

After getting the exact same failure, I've started investigating. Debian installed the binary at `/usr/bin/youtube-dl` instead of `/usr/local/bin/youtube-dl`. After updating the settings for ocDownloader (saw "saved successfully" message), it's still not working.

----

I just noticed: this is only true, if I use the ocDownloader Firefox addon!
Trying to download via ocDownloader directly in nextcloud results in  "YouTube said: Invalid parameters." (probably debian 10 offers an outdated version ...).

Hope this helps debugging the issue!

**Comment by pa4080** [comment]
Hi, I had the same issue on Ubuntu 20.04 and NextCloud 20.0.x. `youtube-dl` is installed manually via curl into `/usr/local/bin` and it is working within CLI. The binary path in NextCloud's settings is `/usr/local/bin/youtube-dl` but the annoying red message exists...

After reading the current discussion, I do made: `sudo ln -s /usr/local/bin/youtube-dl /usr/bin/` ...and now the issue is gone!

**Comment by etyrnal** [comment]
Is it only people who've installed from snap that have this issue?

**Comment by etyrnal** [comment]
Where does ocdownloader look for youtube-dl first?
