### ISSUE TITLE
set referer and useragent

### ISSUE THREAD

**Issue by DJCrashdummy** [e-alfred/ocdownloader#28]
i found this issue at the old project (https://github.com/DjazzLab/ocdownloader/issues/24) and for admins this would be a useful setting.

**Comment by Nibbels** [comment]
Yes this ist definitly something that a hoster might check and block.

For webbots you normally just copy the string from some new firefox or chrome.
Another Header would be:
"**HTTP_ACCEPT**" as "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "*/*", "text/html, application/xhtml+xml, */*", ""
"**HTTP_ACCEPT_CHARSET**" as empty or "utf-8,iso-8859-1,utf-16,*;q=0.001".
"**HTTP_ACCEPT_ENCODING**" as "gzip, deflate" _but the downloader has to understand what it tells the source :D_
"**HTTP_ACCEPT_LANGUAGE**" as "de-DE, en-US" or "de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4"
"**HTTP_USER_AGENT**" as "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36 OPR/47.0.2631.71 (Edition Campaign 75)"
"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0"
"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"
so on.

**Comment by e-alfred** [comment]
This would be a useful feature. But I don't see a possibility to dynamically set the user agent for Aria2c. It only allows to set the user agent for HTTP(S) using the an additional parameter:

https://aria2.github.io/manual/en/html/aria2c.html?highlight=user%20agent#cmdoption-U

For now, it could be added to the readme file on how to set up Aria2. For Curl, an additional setting in the admin settings could be integrated, but it would be very confusing because both downloaders would have different configuration methods for the user agent then.

**Comment by DJCrashdummy** [comment]
the same is valid for referer: https://aria2.github.io/manual/en/html/aria2c.html?highlight=referer#cmdoption--referer

well, we can integrate nearly the whole man-page of `aria2c` into the readme, but that wouldn't make much sense...
i guess people who understand why there are 2 different backends and know how to handle them, also know what to do with a man-page; although a small hint (maybe with an example) is never wrong. :wink: 

---
if it isn't possible to change the useragent and referer for aria2c via the GUI, how are the proxy-settigs achieved?

and if it still isn't possible, i don't see such a big thing with settings only for cURL... there are also settings just for BitTorrent or Youtube. with a hint, that all (other) settings for aria2c must be done via the command line for the daemon, would be perfectly fine (for now).

---

and what do you mean with _"**dynamically** set the user agent"_? - maybe we talk past each other...?
i'm talking about a "simple" setting for the whole instance via admin-setting (ideally in the GUI for all backends).

**Comment by e-alfred** [comment]
@DJCrashdummy By dynamically I mean setting it for each seperate download instead of having one fixed setting in the admin section. This is more useful because different download pages could require different user agents/referers.

I integrated the options to set a referer and user agent in the download section for both http and ftp downloads. Please test it here:  https://github.com/e-alfred/ocdownloader/pull/34

Sample output from Apache logs:

`server - - [17/Sep/2017:15:21:26 +0200] "GET /gallery/file.jpg HTTP/1.1" 200 45280 "http://google.com" "testtmp"`

**Comment by e-alfred** [comment]
Implemented in https://github.com/e-alfred/ocdownloader/pull/34

You can set a user agent and referer in the download section below the link input field for both HTTP/FTP.
