### ISSUE TITLE
downloaded files are shown at 0kb size on nextcloud

### ISSUE THREAD

**Issue by peshane** [e-alfred/ocdownloader#31]
Hi all,

Maybe I missing something:

Just added Aria2 (1.32.0) and youtube-dl on my installation (nextcloud v12.0.2, postgresql 9.6.5) and it working well except that nextcloud show for every downladed files a 0kb size.

I tried a youtube video, http and torrent download and it's the same thing. I tried to disable nextant (freshly installed too) but that change nothing. But, well, I can download or stream downloaded video from nextcloud, that's working.

Only way I found (for now) in order to have the good sizes is to launch an "occ file:scan".
I don't know if it's related to the "0kb size showing" or if it's normal, but *.aria2c files are always in the "Downloads" directory on the filesystem.

**Comment by e-alfred** [comment]
@peshane The problem seems to be that the scanner function not always works as expected. Please try the following:  Open up one of the links on the left pane below "add". This should trigger the scanner function.

The *.aria2c files are stored in the download directory too and should show up in the Nextcloud files app alongside the downloaded files with the right filesizes.

@Nibbels: Do you have an idea what could cause this? It seems to only happen on some installations actually.

**Comment by peshane** [comment]
@e-alfred thanks for your help, this workaround works well \o/

Let me know (and how) if I can provide you some logs.
