### ISSUE TITLE
[low priority] should we rename this app? and if yes, to what?

### ISSUE THREAD

**Issue by DJCrashdummy** [e-alfred/ocdownloader#33]
inspired by the issue (https://github.com/DjazzLab/ocdownloader/issues/58) which had this fork as an result, i opened this issue and collected the suggestions...

just a few annotations to explain the list:
- it is ordered chronological by first mentioning
- the first link is the initial mentioning (sometimes with further explanation, research, etc.)
- additional links are some further discussion or research about it
---
- [_ncDownloader_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319674644) by @e-alfred (additional https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188)
- [_Downloader_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319702563) by @DJCrashdummy
- [_cloudDownloader_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319702563) by @DJCrashdummy (additional https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188)
- [_cloudLoader_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319702563) by @DJCrashdummy
- [_cloudgrabber_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188) by @Nibbels
- [_clou**d**ownloadmanager_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188) by @Nibbels
- [_ownloadmanager_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188) by @Nibbels
- [_ownloader_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-319711188) by @Nibbels
- [_Nextcloud Download Manager (for HTTP, FTP, Torrent and Youtube)_](https://github.com/DjazzLab/ocdownloader/issues/58#issuecomment-321834817) by @e-alfred
- may be extended...

**Comment by e-alfred** [comment]
Well, ncDownloader is basically the name of some kind of badware, so probably not the best choice. The ones with "own" in the name aren't ideal too, because this app is not geared towards that project anymore anyway (it probably still works, but somebody would have to help out with testing).

I have another one: nextDownloader, which isn't used anywhere until now.

**Comment by blackcrack** [comment]
hi, 

well, ownclod-download-er it's outdated. but it works in all clouds what exist as ipen source.. own and nextcloud so, why not easy cloud down loader and making whater ;) "Whatermaker".... nooooo a joke ! :)

Cloud-down-loader so Cloudload or C'load more shortly or Cloudloader ... or "i have no name" because, what's no named be not found ;) (-> Torrent *bg*)
No, in my opinion like you counted, Cloudload or Cloudownloader or easy C'load App ..
naturally works also pritty well, Websucker  ;)

best regards
Blacky

**Comment by sunjam** [comment]
Imho the app name that is the easiest to understand is _Downloader_.  This way it could be described in relevant appstores as Nextcloud Downloader app or Owncloud Downloader app.

**Comment by e-alfred** [comment]
Djazzlab deleted his account and everything related to it, so I don't know if renaming this project is necessary after all.

**Comment by DJCrashdummy** [comment]
hmm... it's a pity that the original project and Djazzlab finally vanished without any reaction. :disappointed: 
thank god (and @e-alfred), it was forked and we've got what we've got! :wink:
