### ISSUE TITLE
Nextcloud 14 - drop of deprecated APIs

### ISSUE THREAD

**Issue by MorrisJobke** [e-alfred/ocdownloader#58]
Hi just want to inform you that with 14 we will drop for example OCP\Config https://github.com/nextcloud/server/pull/7840

See the PHPDoc in that class for how to handle this now.

**Comment by MorrisJobke** [comment]
Please also have a look at https://github.com/nextcloud/server/issues/7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

**Comment by e-alfred** [comment]
Thanks for the info @MorrisJobke!

Is there a new PHPDoc for Nextcloud or is it still located at https://doc.owncloud.org/api/?

**Comment by MorrisJobke** [comment]
> Is there a new PHPDoc for Nextcloud or is it still located at https://doc.owncloud.org/api/?

Best is to have a look at the code directly. Just look into the PR with the deleted code - for example: https://github.com/nextcloud/server/pull/7840/files#diff-152326d1a90608424fb90b9a3b29030cL55

**Comment by e-alfred** [comment]
Okay, the app is now fixed with https://github.com/e-alfred/ocdownloader/commit/25407d08edc3d8bc008cd85a4f279ee3b93729f3 and https://github.com/e-alfred/ocdownloader/commit/c4edc54aa71b58e859e49c9e7338a3ddf0661b78 so it will work with Nextcloud 14. I will leave this open anyway because there surely will be some more changes over time.

**Comment by MorrisJobke** [comment]
Could you replace the OC_API constants in routes.php with the ones from OCP\API?

https://github.com/e-alfred/ocdownloader/blob/0767242591f7bcad94dc390a03a4f77a5ae215d9/appinfo/routes.php#L73

https://github.com/e-alfred/ocdownloader/blob/0767242591f7bcad94dc390a03a4f77a5ae215d9/appinfo/routes.php#L83

https://github.com/e-alfred/ocdownloader/blob/0767242591f7bcad94dc390a03a4f77a5ae215d9/appinfo/routes.php#L93

Or maybe migrate all three methods to the AppFramework?

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/blob/ba87db3fccb40aa58d84d12932424c83a4db411f/lib/public/API.php#L49

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/pull/8788 for the removal of the private namespace constant.

**Comment by e-alfred** [comment]
I fixed the deprecated constants with https://github.com/e-alfred/ocdownloader/commit/217ae7cc68f11133f260e63d4e14e767c70d003c#diff-0e033fd8797499a87a6bf2ffccef5c3c. I am keeping a move to the AppFramework on my TODO list.

**Comment by MorrisJobke** [comment]
> Thanks for the awesome community support!

You are welcome :) Would be sad if it is a that easy fix that could avoid problems in the future ;)

**Comment by e-alfred** [comment]
Yes, it is just that I can't always keep track of all important/serious changes, so it helps quite a bit.

**Comment by MorrisJobke** [comment]
Just want to ping you, @e-alfred 😉

**Comment by e-alfred** [comment]
This should be fixed now.

**Comment by e-alfred** [comment]
I have to reopen this because the OCP\API calls seem to be broken by a recent change making the API unuseable. Maybe @MorrisJobke you can help me with that?

I am getting the following error message in my log:

`{"reqId":"nwxEpX2tXmmmZvAnMPo4","level":3,"time":"2019-04-15T13:14:33+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"POST","url":"\/ocs\/v1.php\/apps\/ocdownloader\/api\/version?format=json","message":"Error: Call to undefined method Exception::getResult() at \/var\/www\/nextcloud\/ocs\/v1.php#71","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.88 Safari\/537.36 Vivaldi\/2.4.1488.36","version":"16.0.0.5"}`

**Comment by MorrisJobke** [comment]
> I am getting the following error message in my log:

Do you mind to show the code that is causing this?

**Comment by e-alfred** [comment]
It is actually this code you also reffered to here https://github.com/e-alfred/ocdownloader/issues/58#issuecomment-372382578: https://github.com/e-alfred/ocdownloader/blob/0987de59499e0d747fef052e25b96a0b332a2ad0/appinfo/routes.php#L66 and https://github.com/e-alfred/ocdownloader/blob/0987de59499e0d747fef052e25b96a0b332a2ad0/controller/lib/api.php#L1.

**Comment by MorrisJobke** [comment]
The OCS API could be used with normal controllers by now. Registration is done in this way:

https://github.com/nextcloud/server/blob/bb58d12bcaf991530be1c526d5de78e473936734/apps/updatenotification/appinfo/routes.php#L29-L31

and the controller is a normal controller returning `DataResponse`'s.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/49dd4afd13f3a58fd591e789d407d10ad09dfa6c.
