### ISSUE TITLE
Can I add --audio-format support for youtube-dl?

### ISSUE THREAD

**Issue by wartw98** [e-alfred/ocdownloader#82]
Can I add --audio-format support for youtube-dl?
Youtube-dl and ffmpeg already exist on the host.
Because you can do this on the web!

**Comment by e-alfred** [comment]
Currently only the best audio quality gets downloaded (see https://github.com/e-alfred/ocdownloader/blob/907902fd10c6a8e1f0c6ed277b2fee4550edb09c/controller/lib/youtube.php#L52). A menu to select different output formats would have to be implemented. Alternatively it could be a simple input box where you could manually type in the preferred format.

**Comment by wartw98** [comment]
After modifying it still appeared webm format he did not perform the conversion action

**Comment by page-work** [comment]
i also try some settings but nothing work! :(

**Comment by archont00** [comment]
This modifiacation of youtube-dl options would not work.

`youtube-dl` is used to find the exact download link only. It is `curl` or `aria` which does download the audio file. Neither of these latter ones can carry out conversion directly.

I am also wondering how to do that - for my purposes, using external tool like `ffmpeg` and some default options would suffice, however I do not know yet how to incorporate that into the code so that the output files are handled by nextcloud correctly.

**Comment by JMPJNS** [comment]
it does the conversion, just doesn't change the filename to the new one

**Comment by JMPJNS** [comment]
it does the conversion, but youtube-dl --get-filename gives the filename before the conversion happened

**Comment by e-alfred** [comment]
You can set the audio format now with this PR: https://github.com/e-alfred/ocdownloader/pull/158

Long term would be to do downloads using youtube-dl (again) instead of just extracting download links for Curl and Aria2.

**Comment by jsellin78** [comment]
Music app in nextcloud only supports mp3 format, is it still possible to download the audio in mp3 format instead of webmin since webin is not supported in browser on Ios android etc
