### ISSUE TITLE
Add mobile view support.

### ISSUE THREAD

**Issue by Gatak** [e-alfred/ocdownloader#95]
It would be great if ocdownloader had a mobile view. Currently some features are blocked in a mobile browser. Especially stop download button...
![screenshot_20180813-183411_opera touch](https://user-images.githubusercontent.com/1469150/44045439-cb353e14-9f28-11e8-9b6c-47aacae5c903.jpg)

**Comment by e-alfred** [comment]
This is mostly fixed by https://github.com/e-alfred/ocdownloader/commit/b3e26b85d4cbeea4b9a9dd0c4f9c3ed22014e58e. 

There is also a mobile (and desktop) app available (created by @bbernhard) for Android and maybe even iOS. If you want to help test it, here is the link to it (also part of the Readme):

https://github.com/bbernhard/nextload-client/issues/1
